# This is a basic workflow to help you get started with Actions
#--------------------------------------------------------------
#
# Copyleft (c) by Andrii Mysyk 2022
#--------------------------------------------------------------

name: My-GitHubActions-Basics

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing job"
  
  
  my-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"
